language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-28.0.3
sudo: required   
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+ 
jdk:
  - oraclejdk8
before_install:
  - yes | sdkmanager "platforms;android-28"
script:
   - ./gradlew build connectedCheck
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"   